cy-data: Treat copying.js.spec afterEach
wearefrank/ladybug-frontend pull request #339
Opened 2024-01-25 10:35 UTC by mhdirkse

2024-01-25 13:13 UTC, philipsens approved these changes

2024-01-26 10:39 UTC, philipsens commented
The tests are failing, should this be resolved first?

2024-01-26 13:29 UTC, MatthijsSmets requested changes
Het lijken nu heel veel comments maar het zijn veel herhalingen, github heeft helaas nog niet de mogelijkheid om meerdere lines te refereren in een comment.
Kort samengevat: 
* Refresh en settings button hebben niks te maken met de tables, daarom table vervangen met button.
* `data-cy-delete-modal-function='confirmDeletion'` is erg lang en heeft dubbele termen daarom kan dit: `data-cy-delete-modal='confirm'` worden
* Settings modal gaat mogelijk een andere component worden dan een modal, daarom graag modal weglaten uit de naam

2024-01-26 13:29 UTC, MatthijsSmets commented on cypress/e2e/transformation.cy.js
> +    cy.get("[data-cy-debug-table='openSettings']").click();
Deze settings button heeft niks te maken met de table
```suggestion
    cy.get("[data-cy-debug-button='settings']").click();
```

2024-01-26 13:29 UTC, MatthijsSmets commented on cypress/support/commands.ts
> +  cy.get("[data-cy-debug-table='openSettings']").click();
Deze settings button heeft niks te maken met de table
```suggestion
    cy.get("[data-cy-debug-button='settings']").click();
```

2024-01-26 13:29 UTC, MatthijsSmets commented on cypress/support/commands.ts
> +  cy.get("[data-cy-settings-modal='saveChanges']").click();
Modal mag je hier weglaten
```suggestion
  cy.get("[data-cy-settings='showAmount']").click();
  cy.get("[data-cy-settings='saveChanges']").click();
```

2024-01-26 13:29 UTC, MatthijsSmets commented on cypress/e2e/settings-component.cy.js
> +    cy.get("[data-cy-settings-modal='close']").click();
Modal mag je hier weglaten
```suggestion
    cy.get("[data-cy-settings='showAmount']").click();
    cy.get("[data-cy-settings='showAmount']").should("have.attr", "value", "true");
    cy.get("[data-cy-settings='close']").click();
```

2024-01-26 13:29 UTC, MatthijsSmets commented on cypress/e2e/settings-component.cy.js
> +    cy.get("[data-cy-settings-modal='close']").click();
Modal mag je hier weglaten
```suggestion
    cy.get("[data-cy-settings='showAmount']").click();
    cy.get("[data-cy-settings='close']").click();
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table-settings-modal/table-settings-modal.component.html
> +    <button id="debugSettingsModalClose" data-cy-settings-modal="close" type="button" class="close"
Modal mag je hier weglaten
```suggestion
    <button id="debugSettingsModalClose" data-cy-settings="close" type="button" class="close"
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table-settings-modal/table-settings-modal.component.html
> +          <input class="btn btn-info my-2 p-1 w-fit" data-cy-settings-modal="showAmount" id="show-multiple"
Modal mag je hier weglaten
```suggestion
          <input class="btn btn-info my-2 p-1 w-fit" data-cy-settings="showAmount" id="show-multiple"
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table-settings-modal/table-settings-modal.component.html
> +          <input class="btn btn-info my-2 p-1 w-fit" data-cy-settings-modal="showSearchOnLoad" id="show-search-on-load"
Modal mag je hier weglaten
```suggestion
          <input class="btn btn-info my-2 p-1 w-fit" data-cy-settings="showSearchOnLoad" id="show-search-on-load"
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table-settings-modal/table-settings-modal.component.html
> +          <select #spacingOptionsDropdown data-cy-settings-modal="spacingDropdown" class="form-control custom-select mr-sm-2"
Modal mag je hier weglaten
```suggestion
          <select #spacingOptionsDropdown data-cy-settings="spacingDropdown" class="form-control custom-select mr-sm-2"
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table-settings-modal/table-settings-modal.component.html
> +      <button data-cy-settings-modal='saveChanges' title="Save changes" type="submit" id="saveTableSettings"
Modal mag je hier weglaten
```suggestion
      <button data-cy-settings='saveChanges' title="Save changes" type="submit" id="saveTableSettings"
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table.component.html
> +    <app-button data-cy-debug-table="refresh" [icon]="'fa fa-refresh'" [title]="'Refresh'" (click)="refresh()"></app-button>
Deze refresh button heeft niks te maken met de table
```suggestion
    <app-button data-cy-debug-button="refresh" [icon]="'fa fa-refresh'" [title]="'Refresh'" (click)="refresh()"></app-button>
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/debug/table/table.component.html
> +    <app-button data-cy-debug-table="openSettings" [icon]="'fa fa-cog'" [title]="'Settings'" (click)="openSettingsModal()"></app-button>
Deze settings button heeft niks te maken met de table
```suggestion
    <app-button data-cy-debug-button="settings" [icon]="'fa fa-cog'" [title]="'Settings'" (click)="openSettingsModal()"></app-button>
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/test/delete-modal/delete-modal.component.html
> +    <button data-cy-delete-modal-function="confirmDeletion" class="btn btn-info" id="confirmDeletion" (click)="deleteReports(); modal.dismiss()">Yes</button>
function mag je hier weglaten en deletion ook aangezien er al delete-modal staat dus: 
```suggestion
    <button data-cy-delete-modal-="confirm" class="btn btn-info" id="confirmDeletion" (click)="deleteReports(); modal.dismiss()">Yes</button>
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/test/test.component.html
> +      <app-button data-cy-test-table="refresh" [icon]="'fa fa-refresh'" [title]="'ReloadTestReports'" (click)="loadData(null)"></app-button>
Deze refresh button heeft niks te maken met de table
```suggestion
      <app-button data-cy-test-button="refresh" [icon]="'fa fa-refresh'" [title]="'ReloadTestReports'" (click)="loadData(null)"></app-button>
```

2024-01-26 13:29 UTC, MatthijsSmets commented on src/app/test/test.component.html
> +      <button data-cy-test-table="upload" type="button" class="btn btn-info my-2 mx-1 px-3"
Upload heeft hier niks te maken met de table
```suggestion
      <button data-cy-test-button="upload" type="button" class="btn btn-info my-2 mx-1 px-3"
```

2024-01-26 14:36 UTC, mhdirkse commented on cypress/e2e/copying.cy.js
>      cy.get("button#CopyButton").click();
Ik dacht dat deze copy button niet boven de tabel staat maar bij de geopende rapporten hoort. Als dat zo is, dan wou ik hem uitstellen om de PR niet te groot te maken. Heb ik het goed gezien?

2024-01-29 10:20 UTC, MatthijsSmets approved these changes
Precies zoals we hadden besproken!

2024-01-30 10:20 UTC, merged