Refactor: stub strategy
wearefrank/ladybug-frontend pull request #564
Opened 2024-07-31 08:01 UTC by ricklue

Refactored stub strategy dropdown that it is using ngModel
When changing the stub strategy, this will open the difference modal, so the user have a confirmation about the change

2024-07-31 08:49 UTC, MarkvdVorst submitted a review, later dismissed

2024-08-01 11:45 UTC, MatthijsSmets commented on src/app/report/edit-display/edit-display.component.ts
Previously changing the stub strategy triggered the `saveChanges` method, but now it doesn't, shouldn't you also add an `ngModelChange` as well to trigger the `saveChanges` method?

2024-08-02 07:56 UTC, ricklue commented on src/app/report/edit-display/edit-display.component.ts
We had a discussion if changing the stub strategy should trigger the `saveChanges` method or should trigger a function where the save button appears, so that was still a question that has to be answered.

2024-08-07 16:57 UTC, MarkvdVorst requested changes
![image](https://github.com/user-attachments/assets/a35517f6-1d76-4551-80ac-65f5808e353f)
When changing the stub strategy, the checkpoint is seen as a report node and then changes the stub strategy dropdown to a rerun button. I don't think this should happen

2024-08-12 11:46 UTC, MarkvdVorst requested changes
There are still two more bugs that I would like to see fixed in this PR if possible.

1. The opened report in the debug view does not update when you save edits.

steps to reproduce:
  - edit report
  - save report
  - go to different checkpoint
  - go to original checkpoint that was edited

The changes do no occur anymore when I switch. Closing and opening the report does show the correct change however.

2. When I edit a checkpoint, add some changes to it and then change the stub strategy, the changes get discarded.
steps to reproduce are the same as above.

The difference between this bug and the previous one is that even with closing and opening the report, the changes did not get saved and are not shown.

2024-08-14 07:55 UTC, MarkvdVorst requested changes
Looking better. I got a new bug now however. I noticed that you made it so the stub strategy cannot be changed while changes are not saved, however when I save the changes inside the edited checkpoint I still get the same warning message. Only switching checkpoints or closing and opening the report fixes this.

![image](https://github.com/user-attachments/assets/95ed69e2-aba7-49d4-bce6-2c22a2401467)

2024-08-14 07:55 UTC, MarkvdVorst commented on src/app/report/difference-modal/difference-modal.component.html
> +              } @else if (!stubChange) {
This should be just an else

2024-08-14 15:56 UTC, MarkvdVorst approved these changes
Looks good. I notice in a lot of cases where multiple toasts are outputted. but for the sake of this issue it's not important for this PR. I'll make a new issue for it on the refactor board and we'll wait to see what @MatthijsSmets thinks about it.

see issue #610

2024-08-14 16:03 UTC, ricklue commented on src/app/report/difference-modal/difference-modal.component.html
> +              } @else if (!stubChange) {
Added the change

2024-08-16 06:39 UTC, merged