Wildcard functionality for the table filter.
wearefrank/ladybug-frontend pull request #565
Opened 2024-07-31 08:27 UTC by MarkvdVorst

Closes #560 

Also added new test for the wildcard functionality and renamed some tests to follow conventions.

2024-08-01 11:45 UTC, MatthijsSmets commented on cypress/e2e/debug_filterTable.cy.js
> +  it('Should change table size when changing display amount', () => {
Yes thank you 🙌

2024-08-01 11:48 UTC, MatthijsSmets requested changes

2024-08-01 11:48 UTC, MatthijsSmets commented on src/app/debug/filter-side-drawer/filter.service.ts
> +          ((metadataType == 'int' || metadataType == 'long') && !this.isValidNumber(value))
Maybe move this assertion to it's own method, I have a hard time reading this.

2024-08-05 13:13 UTC, ricklue approved these changes

2024-08-05 13:30 UTC, merged