Test switching view
wearefrank/ladybug-frontend pull request #788
Opened 2024-11-21 09:02 UTC by mhdirkse

2024-11-21 09:13 UTC, mhdirkse commented
De intentie is hier vooral om het switchen van view te testen. Het wordt hier nog niet afdoende getest dat je werkelijk rapporten kunt verwijderen in de debug tab. Om dat aan te tonen moet je ook een CrudStorage kunnen configureren voor de debug tab. Daarvoor moeten we met verschillende Spring profielen kunnen testen. Dat ga ik in een andere PR doen.

2024-11-26 15:18 UTC, MatthijsSmets requested changes

2024-11-26 15:18 UTC, MatthijsSmets commented on cypress/e2e/debug/deleteReports.cy.ts
> +    // TODO: This should be in beforeEach hook.
I think you forgot one of your todos

2024-11-26 16:23 UTC, MatthijsSmets submitted a review, later dismissed

2024-11-26 16:41 UTC, MatthijsSmets approved these changes

2024-11-26 16:45 UTC, mhdirkse commented on cypress/e2e/debug/deleteReports.cy.ts
> +    // TODO: This should be in beforeEach hook.
Done.

2024-11-26 16:45 UTC, merged