Prepare testing with profiles
wearefrank/ladybug-frontend pull request #789
Opened 2024-11-21 12:17 UTC by mhdirkse

2024-11-21 16:07 UTC, mhdirkse commented
This pull request creates all tests dynamically based on Cypress environment variable "selection". Within test code, this variable can be read with the expression Cypress.env('selection'). Cypress shows errors for spec files that do not have tests. For this reason, I create a dummy test. The name of the dummy test shows the value of Cypress.env('selection') that is the reason for not creating the tests.

The environment variable is set in cypress.env.json. This is better then doing it on the command line, because the command lines appear as scripts in package.json. There are already many scripts for the different ways of testing. If we would make a script for every combination of a test approach and a test selection, the number of scripts would explode.

In GitHub Actions we have a list of all test selections we want to test. This is an array in which each element is a choice for Cypress.env('selection'). Using the GitHub matrix syntax, a job is started for each option. Each option is executed.

Having options to select tests only makes sense if we apply different Spring profiles of the backend for each option. This will be configured by writing frank-runner/specials/ladybug/build.properties. This part is not yet implemented because we do not know what Spring profiles to test with.

2024-11-21 17:05 UTC, mhdirkse commented
De verschillende jobs verschijnen in een pull request als verschillende testen die moeten slagen:
![image](https://github.com/user-attachments/assets/35ce52b0-c615-455f-b75d-32f65f7d4d31)

In de Actions tab is er één scherm waar de verschillende jobs bij elkaar staan:
![image](https://github.com/user-attachments/assets/12662ffa-6d28-4c4f-b7bd-0c7e2e2663eb)

2024-11-21 17:08 UTC, mhdirkse commented
@jacodg je hebt me net uitgelegd welke test met verschillende Spring profielen we nodig hebben. Ik maak deze PR af zodat ook het backend stuk daarvan gedaan wordt. Ik wou nog even uitstellen dat we nog iets te doen hebben voor handmatig testen. Als je handmatig wilt testen, dan moet je met de hand frank-runner/specials/ladybug/build.properties schrijven inclusief de selectie van een Spring profiel. Daarna moet je daar restart.bat of restart.sh starten. Pas als de backend dan draait, dan kan je de frontend testen waarbij je op moet letten dat cypress.env.json goed is. Dat zijn te veel handelingen om aan te denken.

2024-11-22 14:49 UTC, mhdirkse commented
Ik denk dat het zo goed is. De test heeft op vier manieren gedraaid:

* Frontend van ng serve, zonder verandering van Spring profiel.
* Frontend van ng serve, met Spring profiel storage.xml.
* Frontend van backend, zonder verandering van Spring profiel. Faalt omdat de nieuwste testen draaien tegen code waarin de functionaliteit nog niet toegevoegd is.
* Frontend van backend, met Spring profiel storage.xml.

2024-11-26 16:33 UTC, MatthijsSmets requested changes

2024-11-26 16:33 UTC, MatthijsSmets commented on cypress/e2e/copying.cy.ts
> +
I thought we talked about not doing this method and instead group all e2e tests by profile in different folders.

2024-12-03 13:26 UTC, mhdirkse commented
Superseded by https://github.com/wearefrank/ladybug-frontend/pull/803.

2024-12-03 13:26 UTC, closed without merging